// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFavorite(arg1) {
  return window['go']['main']['App']['AddFavorite'](arg1);
}

export function CanEditFile(arg1) {
  return window['go']['main']['App']['CanEditFile'](arg1);
}

export function CheckForUpdates(arg1) {
  return window['go']['main']['App']['CheckForUpdates'](arg1);
}

export function Dirname(arg1) {
  return window['go']['main']['App']['Dirname'](arg1);
}

export function DownloadAndApplyUpdate() {
  return window['go']['main']['App']['DownloadAndApplyUpdate']();
}

export function ExportDOCX(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportDOCX'](arg1, arg2, arg3);
}

export function GetFeedbackSystemInfo() {
  return window['go']['main']['App']['GetFeedbackSystemInfo']();
}

export function GetInitialFile() {
  return window['go']['main']['App']['GetInitialFile']();
}

export function GetPreferences() {
  return window['go']['main']['App']['GetPreferences']();
}

export function GetStartupMode() {
  return window['go']['main']['App']['GetStartupMode']();
}

export function ListFolder(arg1) {
  return window['go']['main']['App']['ListFolder'](arg1);
}

export function NeedsLanguageSelection() {
  return window['go']['main']['App']['NeedsLanguageSelection']();
}

export function NewFile() {
  return window['go']['main']['App']['NewFile']();
}

export function OpenDefaultApps() {
  return window['go']['main']['App']['OpenDefaultApps']();
}

export function OpenExternal(arg1) {
  return window['go']['main']['App']['OpenExternal'](arg1);
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function OpenFolder() {
  return window['go']['main']['App']['OpenFolder']();
}

export function Print() {
  return window['go']['main']['App']['Print']();
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function ReadImageData(arg1, arg2) {
  return window['go']['main']['App']['ReadImageData'](arg1, arg2);
}

export function RemoveFavorite(arg1) {
  return window['go']['main']['App']['RemoveFavorite'](arg1);
}

export function RemoveRecent(arg1) {
  return window['go']['main']['App']['RemoveRecent'](arg1);
}

export function ReportErrorLog(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReportErrorLog'](arg1, arg2, arg3);
}

export function RequestQuit() {
  return window['go']['main']['App']['RequestQuit']();
}

export function SaveAs(arg1, arg2) {
  return window['go']['main']['App']['SaveAs'](arg1, arg2);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SelectFeedbackImages() {
  return window['go']['main']['App']['SelectFeedbackImages']();
}

export function SelectImage(arg1) {
  return window['go']['main']['App']['SelectImage'](arg1);
}

export function SetDirty(arg1) {
  return window['go']['main']['App']['SetDirty'](arg1);
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function SetUsageAnalytics(arg1) {
  return window['go']['main']['App']['SetUsageAnalytics'](arg1);
}

export function ShowInFolder(arg1) {
  return window['go']['main']['App']['ShowInFolder'](arg1);
}

export function SnoozeUpdates(arg1) {
  return window['go']['main']['App']['SnoozeUpdates'](arg1);
}

export function SubmitFeedback(arg1) {
  return window['go']['main']['App']['SubmitFeedback'](arg1);
}
