// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckForUpdates(arg1:boolean):Promise<main.UpdateInfo>;

export function Dirname(arg1:string):Promise<string>;

export function GetInitialFile():Promise<main.Document>;

export function GetPreferences():Promise<main.Preferences>;

export function GetStartupMode():Promise<string>;

export function ListFolder(arg1:string):Promise<main.FolderResult>;

export function NeedsLanguageSelection():Promise<boolean>;

export function NewFile():Promise<main.Document>;

export function OpenDefaultApps():Promise<void>;

export function OpenExternal(arg1:string):Promise<void>;

export function OpenFile():Promise<main.Document>;

export function OpenFolder():Promise<main.FolderResult>;

export function Print():Promise<void>;

export function ReadFile(arg1:string):Promise<main.Document>;

export function ReadImageData(arg1:string,arg2:string):Promise<string>;

export function RemoveRecent(arg1:string):Promise<main.Preferences>;

export function RequestQuit():Promise<boolean>;

export function SaveAs(arg1:string,arg2:string):Promise<main.Document>;

export function SaveFile(arg1:string,arg2:string):Promise<main.Document>;

export function SelectImage(arg1:string):Promise<string>;

export function SetDirty(arg1:boolean):Promise<void>;

export function SetLanguage(arg1:string):Promise<string>;

export function SetTheme(arg1:boolean):Promise<void>;

export function ShowInFolder(arg1:string):Promise<void>;

export function SnoozeUpdates(arg1:number):Promise<void>;
